### ISSUE TITLE
[Feature Request] Python Package

### ISSUE THREAD

**Issue by sebimarkgraf** [ALRhub/wandb2numpy#2]
Hey,

It would be easier to use the package if it can be installed from PyPi instead of the installation from the git repository.
This would provide versioning as well and prevent experiment plotting that should be reproducible from breaking unexpectedly.

If you need a guide for the deployment to PyPi, I can deeply recommend the [hypermodern python series](https://cjolowicz.github.io/posts/hypermodern-python-01-setup/).

**Comment by KoljaBauer** [comment]
Thanks a lot for your suggestion, it is now possible to install it from PyPi!
