### ISSUE TITLE
Nested fields path creation problem

### ISSUE THREAD

**Issue by DenisBless** [ALRhub/wandb2numpy#4]
Hi Kolja, 
first of all thanks for the nice work. 

I found a little problem: If you log values according to

`wandb.log({hierarchy1/hierarchy2: value})`

then I can't use wandb2numpy since 

`fields: ["hierarchy1/hierarchy2:"]`

will raise an error that the path ../hierarchy1/hierarchy2/value.npy does not exist. It would be great if we could fix that so that the package supports nested fields. 

If you have any quesions please let me know. Thanks a lot.

**Comment by KoljaBauer** [comment]
Hi Denis,

thank you for your feedback. Sorry that it took so long to resolve this, there were some unexpected issues with the wandb API. Now it should work properly!
